// DocSection: strongly_typed_models_definition
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/kontent-ai/model-generator-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace KenticoKontentModels
{
    public partial class Homepage
    {
        public const string Codename = "homepage";
        public const string BodyTextCodename = "body_text";
        public const string HeadlineCodename = "headline";
        public const string PictureCodename = "picture";

        public IRichTextContent BodyText { get; set; }
        public string Headline { get; set; }
        public IEnumerable<IAsset> Picture { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}
// EndDocSection
