// DocSection: strongly_typed_models_definition
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace KenticoKontentModels
{
    public partial class Homepage
    {
        public const string Codename = "homepage";
        public const string HeadlineCodename = "headline";
        public const string BodyTextCodename = "body_text";
        public const string PictureCodename = "picture";

        public string Headline { get; set; }
        public IRichTextContent BodyText { get; set; }
        public IEnumerable<Asset> Picture { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}
// EndDocSection