// Tip: Find more about .NET SDKs at https://kontent.ai/learn/net
using Kontent.Ai.Management;
using Kontent.Ai.Management.Configuration;
using Kontent.Ai.Management.Models.Content;
using Kontent.Ai.Management.Models.LanguageVariants;
using Kontent.Ai.Management.Models.LanguageVariants.Elements;
using Kontent.Ai.Management.Models.Shared;
using Kontent.Ai.Management.Models.Workflow;

// Or register it through DI with services.AddManagementClient()
using var client = new ManagementClient(new ManagementOptions
{
    ApiKey = "KONTENT_AI_MANAGEMENT_API_KEY",
    EnvironmentId = "KONTENT_AI_ENVIRONMENT_ID"
});

var identifier = LanguageVariantIdentifier.ByIds(Guid.Parse("f4b3fc05-e988-4dae-9ac1-a94aba566474"), Guid.Parse("d1f95fde-af02-b3b5-bd9e-f232311ccab8"));
// var identifier = LanguageVariantIdentifier.ByCodenames("my_article", "es-ES");

var response = (await client.UpsertLanguageVariantAsync(
    identifier,
    new LanguageVariantUpsertModel
    {
        Elements =
        [
            new TaxonomyElement
            {
                Element = Reference.ByCodename("personas"),
                Value = [Reference.ByCodename("barista"), Reference.ByCodename("coffee_blogger")],
            },
            new DateTimeElement
            {
                Element = Reference.ByCodename("post_date"),
                Value = new DateTimeOffset(2014, 11, 7, 0, 0, 0, TimeSpan.Zero),
                DisplayTimeZone = "Australia/Sydney",
            },
            new TextElement
            {
                Element = Reference.ByCodename("summary"),
                Value = "Tostar granos de café puede tardar de 6 a 13 minutos. ...",
            },
            new LinkedItemsElement
            {
                Element = Reference.ByCodename("related_articles"),
                Value = [Reference.ByCodename("coffee_processing_techniques"), Reference.ByCodename("origins_of_arabica_bourbon")],
            },
            new TextElement
            {
                Element = Reference.ByCodename("meta_keywords"),
                Value = "asados, café",
            },
            new TextElement
            {
                Element = Reference.ByCodename("meta_description"),
                Value = "Tostar granos de café puede tardar de 6 a 13 minutos. ...",
            },
            new UrlSlugElement
            {
                Element = Reference.ByCodename("url_pattern"),
                Mode = UrlSlugMode.Autogenerated,
            },
        ],
        DueDate = new DueDateModel
        {
            Value = new DateTimeOffset(2092, 1, 7, 6, 4, 0, TimeSpan.Zero)
        },
        Note = "Make sure the graphic materials we use here are on brand.",
        Contributors = [UserIdentifier.ByEmail("user@example.com")],
        Workflow = new WorkflowStepIdentifier(Reference.ByDefaultCodename(), Reference.ByCodename("review"))
    })).EnsureSuccess();
