// DocSection: strongly_typed_models_definition
// Tip: Find more about JS/TS SDKs at https://docs.kontent.ai/javascript
import { Elements, IContentItem } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.0.0' at 'Fri, 08 Oct 2021 10:34:09 GMT'
 */
export type Homepage = IContentItem<{
     headline: Elements.TextElement;
     bodyText: Elements.RichTextElement;
     picture: Elements.AssetsElement;
}>;
// EndDocSection