// DocSection: strongly_typed_models_definition
// Tip: Find more about JS/TS SDKs at https://kontent.ai/learn/javascript
import { IContentItem, Elements } from '@kontent-ai/delivery-sdk';

/**
 * Generated by '@kontent-ai/model-generator@5.2.0'
 * Note: Element comments were omitted for brevity.
 */
export type Homepage = IContentItem<{
  headline: Elements.TextElement;
  body_text: Elements.RichTextElement;
  picture: Elements.AssetsElement;
}>;
// EndDocSection