// DocSection: strongly_typed_models_definition
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by 'kentico-cloud-model-generator-utility@2.0.0'
 * Timestamp: Thu Aug 15 2019 15:07:22 GMT+0200 (GMT+02:00)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepage extends ContentItem {
    public headline: Elements.TextElement;
    public bodyText: Elements.RichTextElement;
    public picture: Elements.AssetsElement;
    
    constructor(){
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'body_text'){
                    return 'bodyText';
                }
                return elementName;
            })
        })    
    }  
}
// EndDocSection