/**
 * `CoreContentType` represents the base structure of a content type in Kontent.ai.
 * It provides strongly typed access to system fields such as language, workflow, type, and more.
 *
 * All models are generated by the https://www.npmjs.com/package/@kontent-ai/model-generator
 */
export type Homepage = CoreContentType<
  HomepageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: false
     * Codename: headline
     * Id: 65abffb4-15c9-9b5e-cb0d-7c36300198fb
     * Guidelines: The main headline of your homepage. It can be different than the name in Kontent. Simple text elements don't allow any formatting.
     */
    readonly headline: Elements.TextElement;
    /**
     * Body text
     *
     * Type: rich_text
     * Required: false
     * Codename: body_text
     * Id: 5dc5b1c4-c3b2-14df-65b5-ff5520110bc3
     * Guidelines: Provide main content for the homepage.
     */
    readonly body_text: Elements.RichTextElement<CoreContentType>;
    /**
     * Picture
     *
     * Type: asset
     * Required: false
     * Codename: picture
     * Id: e1cbc227-f1ee-db9e-1831-de36fa4265ed
     * Guidelines: Choose an image to show above the headline.
     */
    readonly picture: Elements.AssetsElement;
  },
  "homepage"
>;

/**
 * Type representing all available element codenames for Homepage
 */
export type HomepageElementCodenames = "headline" | "body_text" | "picture";

/**
 * Type guard for Homepage
 *
 * Id: 078f37bf-b6ce-4fcb-a1d3-be1966c6b50a
 * Codename: homepage
 */
export function isHomepage(
  item: CoreContentType | undefined | null
): item is Homepage {
  return item?.system?.type === "homepage";
}
