import { createDeliveryClient } from "@kontent-ai/delivery-sdk";

// Initializes the Delivery client with `CoreDeliveryClient` type which improves type safety on system fields
// This type is generated by the https://www.npmjs.com/package/@kontent-ai/model-generator
const deliveryClient = createDeliveryClient<CoreDeliveryClient>({
  environmentId: "8d20758c-d74c-4f59-ae04-ee928c0816b7",
});

// Gets an item by codename from Kontent.ai and treats it as a strongly typed model
const homepageItem = (
  await deliveryClient.item<Homepage>("hello_caas_world").toPromise()
).data.item;

// The example above assumes that the item with the codename `hello_caas_world` is of type `Homepage`.
// However, this may not always be the case. To avoid potential runtime errors, it is recommended to
// use generated type guards, such as:
const item = (await deliveryClient.item(`hello_headless_world`).toPromise())
  .data.item;

if (isHomepage(item)) {
  // At this point, the item's type is known, allowing safe and straightforward access to its properties.
  const headline = item.elements.headline.value;
}
